backend:
  name: github
  repo: dee-12-code/portfolio
  branch: main
  auth_scope: repo
  site_domain: https://dee-12-code.github.io/portfolio/
  base_url: https://api.netlify.com

media_folder: "images/uploads" # Folder for uploaded images
public_folder: "/images/uploads"

collections:
  - name: "blog" # Name of the collection
    label: "Blog Posts"
    folder: "content/blog" # Folder to save files
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # URL slug format
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
